[package]
name = "hashguard"
version = "2.0.0"
edition = "2021"
description = "Ensuring the integrity of files through hash sums"
authors = ["javaLux"]
license = "MIT"
repository = "https://github.com/javaLux/hashguard"
readme = "README.md"
keywords = ["cli", "hash", "verify", "file"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "0.3.0"
chksum = "0.3.0"
chrono = "0.4.34"
clap = { version = "4.5.0", features = ["derive", "cargo", "string"] }
color-eyre = "0.6.2"
indicatif = "0.17.8"
log = "0.4.20"
os_info = "3.7.0"
output-coloring = "0.1.0"
path-absolutize = "3.1.1"
percent-encoding = "2.3.1"
regex = "1.10.3"
simple-home-dir = "0.3.2"
simplelog = "0.12.1"
ureq = "2.9.6"
url = "2.5.0"

[profile.release]
opt-level = "z"
