[package]
name = "hashguard"
version = "1.0.7"
edition = "2021"
description = "Ensuring the integrity of files through hash sums"
authors = ["javaLux"]
license = "MIT"
repository = "https://github.com/javaLux/hashguard"
readme = "README.md"
homepage = "https://github.com/javaLux/hashguard"
keywords = ["cli", "hash", "verify", "file"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chksum = "0.2.2"
clap = { version = "4.4.10", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false }
indicatif = "0.17.7"
output-coloring = "0.1.0"
regex = "1.10.2"
ureq = "2.9.1"
url = "2.5.0"

[profile.dev.package.backtrace]
opt-level = 3
