name: Rust

on:
  push:
    branches: [ "main", "feature-**", "patch-**" ]
  pull_request:
    branches: [ "main", "feature-**", "patch-**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_phaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update local toolchain
        run: |
          rustup update
          
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Check and format
        run: |
          cargo fmt
          cargo clippy 

      - name: Run tests
        run: |
          cargo check
          cargo test --all          

      - name: Build
        run: |
          cargo build --release
